apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"wordpress","namespace":"wordpress"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"wordpress"},"type":"ClusterIP"}}
  creationTimestamp: "2026-02-14T07:40:59Z"
  name: wordpress
  namespace: wordpress
  resourceVersion: "20329"
  uid: 3d1308da-8278-448a-a850-a403b816c92c
spec:
  clusterIP: 172.20.220.182
  clusterIPs:
  - 172.20.220.182
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: wordpress
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
